name: Create Flat .tgz Release

on:
  push:
    tags:
      - 'v*' # Örnek: v0.0.5, v1.2.0

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/core

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build package
        run: yarn build

      - name: Prepare flat folder for packaging
        run: |
          mkdir -p temp-pack
          cp -r dist/* temp-pack/
          cp package.json temp-pack/

      - name: Create .tgz package from flat folder
        run: |
          cd temp-pack
          npm pack > ../output.log
          cd ..
          FILE=$(tail -n 1 output.log)
          echo "Packed file: $FILE"
          mv temp-pack/$FILE puck-core-dist.tgz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/core/puck-core-dist.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
