name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/core

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build package
        run: yarn build

      - name: Move dist files to root
        run: |
          mv dist/* .
          echo "Moved dist contents to root:"
          ls -lh

      - name: Pack with npm
        run: |
          npm --ignore-scripts pack
          mv *.tgz puck-core-dist.tgz

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/core/puck-core-dist.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
