name: Create Release with dist

on:
  push:
    tags:
      - 'v*' # örnek: v1.0.0, v2.3.1

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/core

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Archive dist folder
        run: tar -czf puck-core-dist.tgz dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/core/puck-core-dist.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
