name: Create Release with npm pack

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/core

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build package
        run: yarn build

      - name: Create .tgz package with npm pack
        id: pack
        run: |
          echo "Running npm pack..."
          npm pack > output.log
          FILE=$(tail -n 1 output.log)
          echo "Packed file: $FILE"
          mv "$FILE" puck-core-dist.tgz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/core/puck-core-dist.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
